config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:omniauth_callbacks => "omniauth_callbacks"}
  root 'home#index'

  
  get 'places/new' => 'places#new'
  post 'places' => 'places#create'

  get 'places/search' => 'places#search'
  get 'places/:id' => 'places#show'

  post 'sessions/store_location' => 'sessions#store_location' 
  get 'favourite_lists' => 'favourite_lists#index'
  post 'favourite_lists' => 'favourite_lists#create'

  get 'favourite_lists/:id' => 'favourite_lists#show', as: :favourite_list_show

  resources :feedbacks, 
  only: [:new, :create]
  get '/feedbacks' => 'feedbacks#new'
  resources :places, only: [:index] do 
    resources :reports, only: [:new, :create]
  end
    get '/places/:place_id/reports' => 'reports#new'

end

app/models/favourite_list.rb
class FavouriteList  < ActiveRecord::Base
	belongs_to :user
	has_many :list_places, dependent: :delete_all
end

app/models/list_place.rb
class ListPlace < ActiveRecord::Base
	belongs_to :places
	belongs_to :favourite_list
end

app/models/place.rb
class Place < ActiveRecord::Base
	mount_uploaders :avatars, AvatarUploader
	belongs_to :list_place
	acts_as_taggable
	acts_as_taggable_on :tags
	has_many :place_categories
	has_many :reports
	geocoded_by :get_address
	after_validation :geocode, :if => lambda{ |obj| obj.address_changed? }

	def address_changed?
		self.line_changed? || self.line2_changed? || self.postcode_changed? || self.city_changed? || self.country_changed?
	end

	def coordinates_exist?
		!(self.longitude.nil? || self.latitude.nil?)
	end


	private 
	def get_address
		address = "#{self.line} #{self.line2} #{self.postcode} #{self.city} #{self.country}"
	end 

	
end

app/models/report.rb
class Report < ActiveRecord::Base
	belongs_to :place
end

app/models/user.rb
class User < ActiveRecord::Base

  mount_uploader :avatar, AvatarUploader
  has_one :favourite_list, dependent: :delete
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, 
         :omniauthable, :omniauth_providers => [:facebook]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.username = auth.info.name
      user.age = auth.extra.raw_info.birthday
      user.gender = auth.extra.raw_info.gender
      user.image_url = auth.info.image
      user.email = auth.info.email
      user.provider = auth.provider
      user.remote_avatar_url = auth.info.image.gsub('http://','https://')
      user.password = Devise.friendly_token[0,20]
      user.save!
    end
  end
  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerns/get_user_location.rb
module GetUserLocation
	extend ActiveSupport::Concern
	included do

		# before_action :authenticate_user!
		before_action :get_latitude_longitude
		attr_reader :latitude, :longitude
	end
	def get_latitude_longitude
		@latitude = session[:latitude].to_f unless session[:latitude].nil?
		@longitude = session[:longitude].to_f unless session[:longitude].nil?
		if @latitude.nil? || @longitude.nil?
			result = Geocoder.search(current_user.current_sign_in_ip.to_s)
			@latitude = result.data[:latitude].to_f
			@longitude = result.data[:longitude].to_f
		end
		
	end

end 

app/controllers/favourite_lists_controller.rb
class FavouriteListsController < ApplicationController
  def index
    # byebug
  end

  def create
  	# user_id = current_user.id
  	favourite_list = FavouriteList.new(user_id: current_user.id, name: current_user.username)
  	if favourite_list.save!
  		places_id = params[:places_id]
  		places_id.each do |place_id|
  			list_place = ListPlace.new(favourite_list_id: favourite_list.id, place_id: place_id)
  			unless list_place.save
  				favourite_list.destroy
  				break
  			end
	  	end
      # byebug
      respond_to do |format|
        format.json { render json: {favourite_list_id: favourite_list.id}}
      end
      # redirect_to favourite_list_show_path(favourite_list.id)
  	else
  	end
  	# render :nothing => true
  end

  def show
    favourite_list = FavouriteList.find(params[:id])
    place_id = favourite_list.list_places.pluck(:place_id)
    @places = Place.where(id: place_id)
  end
end

app/controllers/feedbacks_controller.rb
require_relative '../jobs/feedbackjob'

class FeedbacksController < ApplicationController
  def index
  end

  def create 
  	# byebug
	FeedbackJob.perform_later(@customer, @host, current_user, feedback_params[:body])
  end

  private

  def feedback_params
  	params.require(:feedback).permit(:body)
  end
end  	
# def create
#     # @reservation = current_user.reservations.new(reservation_params)
#     @reservation = Reservation.new(reservation_params)
#     @reservation.user_id = current_user.id
#     @listing = Listing.find(params[:listing_id])
    
#     @customer = current_user
#     # @reservation.listing_id = params[:listing_id]
#     respond_to do |format|
#       if @reservation.save
#         format.html { redirect_to listing_reservation_url(@listing,@reservation), notice: 'Reservation was successfully created.' }
#         format.json { render :show, status: :created, location: @reservation }
#         ReservationMailer.booking_email(@customer, @host, @reservation_id).deliver_now
#         ReservationMailer.customer_email(@customer, @host).deliver_now
#       else
#         format.html { render :edit }
#         format.json { render json: @reservation.errors, status: :unprocessable_entity }
#       end
#     end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	include GetUserLocation
  def index
  	# byebug
  	if params[:search].nil? 
  		@places = Place.near([latitude, longitude], 20,:units => :km)
  		gon.places = @places
  		respond_to do |format|
  		    format.html
  		end
  	else
  		@places = Place.near(params[:search], 20, :units => :km)
  		gon.places = @places
  		respond_to do |format|
  		    format.js
  		end
  	end
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
	def facebook
		@user = User.from_omniauth(request.env["omniauth.auth"])
		if @user.persisted?
			sign_in_and_redirect @user
			set_flash_message(:notice, :success,:kind=>"Facebook") if is_navigational_format?
		else
			session["devise.facebook_data"] = request.env["omniauth.auth"]
			redirect_to new_user_registration_url
		end
	end

	def failure
		redirect_to root_path
	end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
	include GetUserLocation
	def new
		@place = Place.new
	end

	def show
		byebug
	end

	def create
		@place = Place.new(place_params)
		if @place.save
			if @place.coordinates_exist?
				#need to do something if the given address's coordinates cannot be found
			end
			redirect_to root_path
		else
			redirect_to places_new_path
		end
	end

	def index
	end

	def search
		@places = Place.near(params[:search], 20, :units => :km)
		gon.places = @places
	end

	private
	def place_params
		params.require(:place).permit(:line,:line2,:postcode,:city,:country,:name,:user_id,
			:verified_at,:description,:open_at,:close_at,:phone,:email,:website,:latitude,:longitude,{avatars: []},:tag_list)
	end


end

app/controllers/reports_controller.rb
require_relative '../jobs/reportjob'
class ReportsController < ApplicationController
  def index
  end

  def create 
  	ReportJob.perform_later(@customer, @host, current_user, report_params[:body])
  end

  private

  def report_params
  	params.require(:report).permit(:body)
  end
end  	

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def store_location
		session[:latitude] = params[:latitude]
		session[:longitude] = params[:longitude]
		render :nothing => true
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/favourite_lists/show.html.erb
<h2>favourite list</h2>
<% @places.each_with_index do |place, pi| %>
	<div>
		<%= "#{pi+1}. #{place.name}" %>
	</div>
<% end %>

app/views/feedbacks/_form.html.erb
<h1>You have successfully given your feedback</h1>
<%= link_to 'Back', root_path %>

app/views/feedbacks/create.html.erb
<%= render "feedbacks/form" %>

app/views/feedbacks/new.html.erb
<div id="boxes">
  <div id="dialog" class="window">
<h1>New Feedback</h1>
<%= form_for(:feedback, url: feedbacks_path) do |f| %>
  <%= f.text_field :body %>
  <%= submit_tag 'Send' %> 
<% end %>
<%= link_to 'Back', root_path %> 
  </div>
  <div id="mask"></div>
</div>
<script>
$(document).ready(function() {	

var id = '#dialog';
	
//Get the screen height and width
var maskHeight = $(document).height();
var maskWidth = $(window).width();
	
//Set heigth and width to mask to fill up the whole screen
$('#mask').css({'width':maskWidth,'height':maskHeight});

//transition effect
$('#mask').fadeIn(500);	
$('#mask').fadeTo("slow",0.9);	
	
//Get the window height and width
var winH = $(window).height();
var winW = $(window).width();
              
//Set the popup window to center
$(id).css('top',  winH/2-$(id).height()/2);
$(id).css('left', winW/2-$(id).width()/2);
	
//transition effect
$(id).fadeIn(2000); 	
	
//if close button is clicked
$('.window .close').click(function (e) {
//Cancel the link behavior
e.preventDefault();

$('#mask').hide();
$('.window').hide();
});

//if mask is clicked
$('#mask').click(function () {
$(this).hide();
$('.window').hide();
});
	
});
</script>

app/views/home/index.html.erb
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<%if current_user%>

<input type="checkbox" id="sidebartoggler" name="" value="">

<div class="page-wrap">

  <nav id="navbar">
  <div>
    <div class="float_left_nav">

    <label for="sidebartoggler" class="toggle"><div class="hamb"></div><div class="hamb" style=""></div><div class="hamb"></div></label>

    <a href="#"></a><img id="placero" src="assets/logoicon.png"></a>
      <img src="assets/heart.png" id="heart">
    </div>
    
    <div class="float_right_nav">
    <img id="filter" src="assets/filter.png">
      <a href="/places/new"><img id="create" src="assets/create.png"></a>
    </div>

  </div>

  
  </nav>
  
  <div>
    <div class="float_right">
      <div class="content">
      </div>
    </div>
  
 
    <div class="float_left">

      <div class="sidebar">
      <ul>
        <li><a href="#"><img src="<%= current_user.avatar.medium_avatar.url %>" class="circular-image" /></a>
          <%= current_user.username %></li>
        <li><img id="switch" src="assets/Switch.png">Location Setting</li>
        <li><img id="view" src="assets/View.png">My Placero</li>
        <li><img id="contact" src="assets/Contact.png">Contact Placero</li>
        <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
      </ul>
      </div> 

   </div>


<% else %>

<html>
      <div class="loginpage"><img id= "mainlogo" src="assets/logo.png"> </div>
      <div class="facebooklogin"><%= link_to image_tag("/assets/facebookbutton.png", :class=>"fbbutton"),user_omniauth_authorize_path(:facebook) %>
      </div>
</html>

 <% end %>
  <!-- Slider main container -->
  
 <script>
$(document).ready(function(){     
    if (!navigator.geolocation){
      output.innerHTML = "<p>Geolocation is not supported by your browser</p>";
      return;
    }

    function success(position) {
      var latitude  = position.coords.latitude;
      var longitude = position.coords.longitude;

      // output.innerHTML = '<p>Latitude is ' + latitude + '° <br>Longitude is ' + longitude + '°</p>';
      $.ajax({
          method: 'post',
          url: '/sessions/store_location',
          data: {latitude: latitude, longitude: longitude}
          });
    };

    function error() {
      // output.innerHTML = "Unable to retrieve your location";
    };

    // output.innerHTML = "<p>Locating…</p>";

    navigator.geolocation.getCurrentPosition(success, error);
    var places = gon.places;
    var number_of_places = places.length;
    var initial_number = 0;
    var saved_list = [];
    
     addNewProfile();
     $("#heart").click(function(){
      if(saved_list.length <= 0){
        alert("you haven't liked any place yet...")
      }
      else{
        $.ajax({
            method: 'post',
            url: '/favourite_lists',
            data: {places_id: saved_list},
            success: function(data){
                var full = location.protocol+'//'+location.hostname+(location.port ? ':'+location.port: '');
                // console.log(initial_number + ":" + places[initial_number].name);
                window.location.href = full+"/favourite_lists/"+data.favourite_list_id;
              },
            fail: function(data){
              alert("can't save your list")
            } 
            });
      }
     });
     function swipe() {
       Draggable.create("#photo", {
           throwProps:true,
           onDragEnd:function(endX) {
              initial_number++    
             if(Math.round(this.endX) > 0 ) {
               swipeLike();
             }
             else {
               swipeDislike();
             }
         },
         onClick:function(){
          var currentPlace = places[initial_number]
          var full = location.protocol+'//'+location.hostname+(location.port ? ':'+location.port: '');
          // console.log(initial_number + ":" + places[initial_number].name);
          window.location.href = full+"/places/"+currentPlace.id;
         }
       });
     }

     function swipeLike() {
       
         var $photo = $("div.content").find('#photo');

         var swipe = new TimelineMax({repeat:0, yoyo:false, repeatDelay:0, onComplete:remove, onCompleteParams:[$photo]});
         swipe.staggerTo($photo, 0.8, {bezier:[{left:"+=400", top:"+=300", rotation:"60"}], ease:Power1.easeInOut});
         
         saved_list.push(places[initial_number-1].id)
         addNewProfile();
     }

     function swipeDislike() {
       
         var $photo = $("div.content").find('#photo');

         var swipe = new TimelineMax({repeat:0, yoyo:false, repeatDelay:0, onComplete:remove, onCompleteParams:[$photo]});
         swipe.staggerTo($photo, 0.8, {bezier:[{left:"+=-350", top:"+=300", rotation:"-60"}], ease:Power1.easeInOut});
         addNewProfile();
     }

     function remove(photo) {
         $(photo).remove();
     }

     function addNewProfile() {
      if(initial_number < number_of_places ){
        var url = places[initial_number].avatars[0].url
        $("div.content").prepend("<div class='photo' id='photo' style='position: absolute; background-image:url("+url+")'>" 
          + "<div class='photo-name'>"
          + places[initial_number].name
          + '</div'
          + '</div>');
          swipe();
      }
      else{
        alert("finish")
      }
     };
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Placero</title>
  <%= include_gon %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag "application.css" %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
  <script src="http://cdnjs.cloudflare.com/ajax/libs/gsap/latest/plugins/CSSPlugin.min.js"></script>
  <script src="http://cdnjs.cloudflare.com/ajax/libs/gsap/latest/easing/EasePack.min.js"></script>
  <script src="http://cdnjs.cloudflare.com/ajax/libs/gsap/latest/TweenLite.min.js"></script>
  <script src="http://cdnjs.cloudflare.com/ajax/libs/gsap/latest/TweenMax.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/1.15.0/utils/Draggable.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
  <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
</head>
<body>
  <div>   
  
  </div>
<%= yield %>
</body>
</html>
<script>
  $.ajaxSetup({
    headers: {
      'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
    }
  });
</script>

app/views/places/_place.html.erb
<% @places.each_with_index do |place,pi| %>
	<div>
		<%= "#{pi+1}. #{place.name}" %><br>
		<% if place.longitude.nil? || place.latitude.nil? %>
			<%= "*this location coordinate is incomplete" %>
		<% else %>
			<%= "latitude: #{place.latitude}, longitude: #{place.longitude}" %>
			<%= button_to 'Report', new_place_report_path(place), :method => "get" %>
		<% end %>
	</div>
<% end %>

app/views/places/index.html.erb
<h2>All places</h2>

  <div style="padding-top: 400px;">
    <%= form_tag places_search_path, method: :get, remote: true do |f| %>
        <p>
          <%= text_field_tag :search, params[:search] %>
          <%= submit_tag "Search", name: nil %>
        </p>
    <% end %>
    <div id="my_search">
      <p><strong>Nearby me</strong></p>
    </div>
    <div id="search_places">
      <%= render 'place' %>
    </div>
  </div>
  
<div class="container">
  <div class="slider">
    <input type = "range" min="0" max="30" onchange="rangevalue.value=value"/>
	  <output id="rangevalue">15</output>
  </div>
</div>
<script>
  $(document).ready(function() {
    
  });
</script>

app/views/places/new.html.erb
<div class="top_bar">

<a href="/"><div id="create_nav"><img class="arrow" src="/assets/backarrow.png"> Create New Place</div></a>

</div>

<div class="center_form">
<%= form_for @place, url: places_path do |f| %>
    
<div class="float_left_form">
   
	<div>
		<%= f.label "Name" %><br>
		<%= f.text_field :name %>
	</div>
	<div>
		<%= f.label "Email" %><br>
		<%= f.email_field :email %>
	</div>
	<div>
		<%= f.label "Address line" %><br>
		<%= f.text_field :line %>
	</div>
	<div>
		<%= f.label "Address line 2" %><br>
		<%= f.text_field :line2 %>
	</div>
</div>

<div class="float_right_form">
	<div>
		<%= f.label "Postcode" %><br>
		<%= f.text_field :postcode %>
	</div>
	<div>
		<%= f.label "City" %><br>
		<%= f.text_field :city %>
	</div>
	<div>
		<%= f.label "Country" %><br>
		<%= f.text_field :country %>
	</div>
	<div>
		<%= f.file_field :avatars, multiple: true %>
	</div>	
	<div>
		<%= f.label :tag_list, "Tags (seperated by commas)" %><br>
		<%= f.text_field :tag_list %>
	</div>
	<div>
		<%= f.submit %>
	</div>
</div>
<% end %>

app/views/places/search.js.erb
 $(document).ready(function(event) {
      $('#my_search').text('New location')
      $("#search_places").html("<%= escape_javascript(render('place')) %>");
    });

app/views/reports/_form.html.erb
<h1>You have successfully submitted your report</h1>
<%= link_to 'Back', places_path %>

app/views/reports/create.html.erb
<%= render "reports/form" %>

app/views/reports/new.html.erb
<div id="boxes">
  <div id="dialog" class="window">
<h1>Please submit your reports below</h1>
<%= form_for(:report, url: place_reports_path) do |f| %>
  <%= f.text_field :body %>
  <%= submit_tag 'Send' %> 
<% end %>

<%= link_to 'Back', places_path %>
  </div>
  <div id="mask"></div>
</div>
<script>
$(document).ready(function() {	

var id = '#dialog';
	
//Get the screen height and width
var maskHeight = $(document).height();
var maskWidth = $(window).width();
	
//Set heigth and width to mask to fill up the whole screen
$('#mask').css({'width':maskWidth,'height':maskHeight});

//transition effect
$('#mask').fadeIn(500);	
$('#mask').fadeTo("slow",0.9);	
	
//Get the window height and width
var winH = $(window).height();
var winW = $(window).width();
              
//Set the popup window to center
$(id).css('top',  winH/2-$(id).height()/2);
$(id).css('left', winW/2-$(id).width()/2);
	
//transition effect
$(id).fadeIn(2000); 	
	
//if close button is clicked
$('.window .close').click(function (e) {
//Cancel the link behavior
e.preventDefault();

$('#mask').hide();
$('.window').hide();
});

//if mask is clicked
$('#mask').click(function () {
$(this).hide();
$('.window').hide();
});
	
});
</script>